_wandb:
    value:
        cli_version: 0.23.0
        e:
            oqnndoenc3ceikmi1cwtzyf24llh1j6k:
                args:
                    - --max-metric-calls
                    - "10"
                codePath: examples/polynomial/main.py
                codePathLocal: examples/polynomial/main.py
                cpu_count: 72
                cpu_count_logical: 144
                disk:
                    /:
                        total: "34359738368"
                        used: "3548741632"
                email: lukeleeai@gmail.com
                executable: /data/lukedhlee/gepa_luke/.optany/bin/python
                git:
                    commit: 95a62af768aab42f4851bfd8f684e1ba85958aff
                    remote: git@github.com:gepa-ai/gepa-optimize-anything.git
                host: havoc
                memory:
                    total: "1082017275904"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: /data/lukedhlee/gepa_luke/gepa-optimize-anything/examples/polynomial/main.py
                python: CPython 3.12.3
                root: /data/lukedhlee/gepa_luke/gepa-optimize-anything
                startedAt: "2025-12-03T05:45:39.080204Z"
                writerId: oqnndoenc3ceikmi1cwtzyf24llh1j6k
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 95
                - 105
                - 107
            "2":
                - 95
                - 105
                - 107
            "3":
                - 2
                - 13
                - 61
            "4": 3.12.3
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
